### ISSUE TITLE
Typo: https://webpagefx.mangoapps.com/msc/NjM3MjMzXzg3NDE0NzQ

### ISSUE THREAD

**Issue by WebFX-dev** [chrisputnam9/quixer#99]
https://webpagefx.mangoapps.com/msc/NjM3MjMzXzg3NDE0NzQ - Default should be: https://food52.com/recipes

**Comment by chrisputnam9** [comment]
Fixed - thanks!

**Comment by WebFX-dev** [comment]
chrisputnam9/quixer,

Thank you for submitting your website request! This email is to confirm that your request has been received and added to our ticket queue. One of the WebFX Support team members will begin working on the ticket as soon as possible, and respond to you when complete.

You can check the status of or reply to the ticket at the following link: http://helpdesk.webpagefx.com/index.php?_m=tickets&_a=viewticket&ticketid=169051

    Using the following login:
    E-mail: ***@***.***
    Password: fcda5d5b


***If your website is down, and it is currently outside of our business hours of 8AM-5PM EST Monday through Friday, please call 717-609-0360 and select option #2.***

Thank you!
- WebFX Support Team

**Comment by WebFX-dev** [comment]
chrisputnam9/quixer,

Thank you for submitting your website request! This email is to confirm that your request has been received and added to our ticket queue. One of the WebFX Support team members will begin working on the ticket as soon as possible, and respond to you when complete.

You can check the status of or reply to the ticket at the following link: http://helpdesk.webpagefx.com/index.php?_m=tickets&_a=viewticket&ticketid=169052

    Using the following login:
    E-mail: ***@***.***
    Password: d16e45fd


***If your website is down, and it is currently outside of our business hours of 8AM-5PM EST Monday through Friday, please call 717-609-0360 and select option #2.***

Thank you!
- WebFX Support Team
